### ISSUE TITLE
Can't install from PyPl

### ISSUE THREAD

**Issue by profPlum** [hercules-team/python-augeas#54]
Python version: 3.7.6
Pip version:  20.0.2
System: Linux, `uname -v` output --> #53~18.04.1-Ubuntu SMP Thu Jul 15 11:32:10 UTC 2021
(this is either a debian or ubuntu system... probably ubuntu)

`pip install python-augeas` gives me this error:

ERROR: Command errored out with exit status 1:
     command: /home/dwyerdeighan/anaconda3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o0jh7i56/python-augeas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o0jh7i56/python-augeas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-o0jh7i56/python-augeas/pip-egg-info
         cwd: /tmp/pip-install-o0jh7i56/python-augeas/
    Complete output (31 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o0jh7i56/python-augeas/setup.py", line 43, in <module>
        test_suite="test.test_augeas",
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "augeas/ffi.py", line 47, in <module>
        lib = ffi.dlopen("augeas")
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 150, in dlopen
        lib, function_cache = _make_ffi_library(self, name, flags)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 832, in _make_ffi_library
        backendlib = _load_backend_lib(backend, libname, flags)
      File "/home/dwyerdeighan/anaconda3/lib/python3.7/site-packages/cffi/api.py", line 827, in _load_backend_lib
        raise OSError(msg)
    OSError: ctypes.util.find_library() did not manage to locate a library called 'augeas'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by thedrow** [comment]
You need to have the augeas library installed in order to compile this library.
